import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar"
import { GeistSans } from 'geist/font/sans';
import { ThemeProvider } from "@/components/theme-provider"



// const geistSans = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EVri Component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className}`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
